library(dplyr)

# Create a clean lookup table
stadium_lookup <- tibble::tribble(
  ~original_stadium, ~clean_stadium, ~home_team, ~city,
  "Sydney Showground Stadium", "Sydney Showground Stadium", "Sydney Thunder", "Sydney",
  "Adelaide Oval", "Adelaide Oval", "Adelaide Strikers", "Adelaide",
  "Docklands Stadium", "Marvel Stadium", "Melbourne Renegades", "Melbourne",
  "Sydney Cricket Ground", "Sydney Cricket Ground (SCG)", "Sydney Sixers", "Sydney",
  "Western Australia Cricket Association Ground", "WACA Ground", "Western Australia", "Perth",
  "Bellerive Oval", "Bellerive Oval (Ninja Stadium)", "Hobart Hurricanes", "Hobart",
  "Brisbane Cricket Ground, Woolloongabba", "The Gabba", "Brisbane Heat", "Brisbane",
  "Melbourne Cricket Ground", "Melbourne Cricket Ground (MCG)", "Melbourne Stars", "Melbourne",
  "W.A.C.A. Ground", "WACA Ground", "Western Australia", "Perth",
  "Aurora Stadium", "University of Tasmania Stadium", "Hobart Hurricanes", "Launceston",
  "Simonds Stadium, South Geelong, Victoria", "Kardinia Park (GMHBA Stadium)", "Melbourne Renegades", "Geelong",
  "Traeger Park", "Traeger Park", "Hobart Hurricanes", "Alice Springs",
  "Manuka Oval", "Manuka Oval", "Sydney Thunder", "Canberra",
  "Perth Stadium", "Optus Stadium", "Perth Scorchers", "Perth",
  "Carrara Oval", "Metricon Stadium (Carrara Stadium)", "Brisbane Heat", "Gold Coast",
  "Geelong Cricket Ground", "Kardinia Park (GMHBA Stadium)", "Melbourne Renegades", "Geelong",
  "Ted Summerton Reserve", "Ted Summerton Reserve", "Melbourne Stars", "Moe",
  "International Sports Stadium", "International Sports Stadium (Coffs Harbour)", "Sydney Sixers", "Coffs Harbour",
  "Brisbane Cricket Ground", "The Gabba", "Brisbane Heat", "Brisbane",
  "Manuka Oval, Canberra", "Manuka Oval", "Sydney Thunder", "Canberra",
  "Docklands Stadium, Melbourne", "Marvel Stadium", "Melbourne Renegades", "Melbourne",
  "Aurora Stadium, Launceston", "University of Tasmania Stadium", "Hobart Hurricanes", "Launceston",
  "Bellerive Oval, Hobart", "Bellerive Oval (Ninja Stadium)", "Hobart Hurricanes", "Hobart",
  "Brisbane Cricket Ground, Woolloongabba, Brisbane", "The Gabba", "Brisbane Heat", "Brisbane",
  "GMHBA Stadium, South Geelong, Victoria", "Kardinia Park (GMHBA Stadium)", "Melbourne Renegades", "Geelong",
  "Junction Oval, Melbourne", "Junction Oval", "Melbourne Stars", "Melbourne",
  "International Sports Stadium, Coffs Harbour", "International Sports Stadium (Coffs Harbour)", "Sydney Sixers", "Coffs Harbour",
  "Cazaly's Stadium, Cairns", "Cazalys Stadium", "Brisbane Heat", "Cairns",
  "University of Tasmania Stadium, Launceston", "University of Tasmania Stadium", "Hobart Hurricanes", "Launceston",
  "Lavington Sports Oval, Albury", "Lavington Sports Oval", "Sydney Thunder", "Albury",
  "North Sydney Oval, Sydney", "North Sydney Oval", "Sydney Sixers", "Sydney",
  "Stadium Australia", "Stadium Australia", "Sydney Thunder", "Sydney",
  "Optus Stadium", "Optus Stadium", "Perth Scorchers", "Perth",
  "SCG", "Sydney Cricket Ground (SCG)", "Sydney Sixers", "Sydney",
  "The Gabba", "The Gabba", "Brisbane Heat", "Brisbane",
  "Marvel Stadium", "Marvel Stadium", "Melbourne Renegades", "Melbourne",
  "MCG", "Melbourne Cricket Ground (MCG)", "Melbourne Stars", "Melbourne",
  "Coffs Harbour International Stadium", "International Sports Stadium (Coffs Harbour)", "Sydney Sixers", "Coffs Harbour",
  "GMHBA Stadium", "Kardinia Park (GMHBA Stadium)", "Melbourne Renegades", "Geelong",
  "Carrara Stadium", "Metricon Stadium (Carrara Stadium)", "Brisbane Heat", "Gold Coast",
  "Lavington Sports Ground", "Lavington Sports Oval", "Sydney Thunder", "Albury",
  "University Of Tasmania Stadium", "University of Tasmania Stadium", "Hobart Hurricanes", "Launceston",
  "Metricon Stadium", "Metricon Stadium (Carrara Stadium)", "Brisbane Heat", "Gold Coast",
  "Junction Oval", "Junction Oval", "Melbourne Stars", "Melbourne",
  "Cazalys Stadium", "Cazalys Stadium", "Brisbane Heat", "Cairns",
  "C.ex Coffs International Stadium", "International Sports Stadium (Coffs Harbour)", "Sydney Sixers", "Coffs Harbour",
  "WACA Ground", "WACA Ground", "Western Australia", "Perth",
  "ANZ Stadium", "Stadium Australia", "Sydney Thunder", "Sydney"
)
